/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimiento;

import Repositorios.Alien;
import Repositorios.Bala;
import Repositorios.Hilo_Bala;
import Repositorios.MovimientoCara;
import Repositorios.Nave;
import Repositorios.disparoPajaro;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Clint
 */
public class Ventana extends javax.swing.JFrame {
    
    ArrayList<Hilo_Bala> hilos;
    
    ArrayList<Alien> aliens;
    
    int nAliens = 3;
    
    int y = 100;
    int x = 100;
    int inc = 10;
    int j = 0;
    Nave nave;
    

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        
        
        initComponents();
        //ImageIcon imagen = new ImageIcon("img/bala2.png");
        //cañon.setIcon(imagen);
        hilos = new ArrayList<>();
        aliens = new ArrayList<>();
        
        nave = new Nave();
        nave.setX( this.getWidth()/2 );
        nave.setY( this.getHeight()-nave.getImagen().getHeight(this) -100 );
        nave.setVentana(this);
        
        
        
        for(j = 0; j < nAliens; j++){
            Alien alien = new Alien();
            alien = new Alien();
            alien.setX(j*100);
            alien.setY(40);
            alien.setVentana(this);
            aliens.add(alien);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
        
        
        if(evt.getKeyCode()==39){
            nave.derecha();
        }
        else if(evt.getKeyCode()==37){
            nave.izquierda();
        }
        else if(evt.getKeyCode() == 38){
            nave.disparar();
            
        }
        
        if(evt.getKeyChar()=='x'){
        
        }
        
        if(evt.getKeyChar()=='c'){
        
        }
        
        if(evt.getKeyChar()=='v'){
        
        }
        
        if(evt.getKeyChar()=='b'){
        
        }
        
        if(evt.getKeyChar()=='z'){
        
        }
    }//GEN-LAST:event_formKeyPressed

    
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        for(int i = 0; i < hilos.size(); i++){
            g.drawImage(hilos.get(i).getBala().getImagen(), hilos.get(i).getBala().getX(), hilos.get(i).getBala().getY(), this);
        }
        
        g.drawImage(nave.getImagen(), nave.getX(), nave.getY(), this);
        for(int j = 0; j < aliens.size();j++){
            
            g.drawImage(aliens.get(j).getImagen(), aliens.get(j).getX(), aliens.get(j).getY(), this);
        }
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    public ArrayList<Alien> getAliens() {
        return aliens;
    }

    public void setAliens(ArrayList<Alien> aliens) {
        this.aliens = aliens;
    }

    public ArrayList<Hilo_Bala> getHilos() {
        return hilos;
    }

    public void setHilos(ArrayList<Hilo_Bala> hilos) {
        this.hilos = hilos;
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
